spring:
  profiles:
    active: dev
  jackson:
    #不响应value=null的字段
    default-property-inclusion: non_null
    #日期响应格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.13.113.35:3306/uavms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: uav-admin
      password: 123456
      ###################以下为druid增加的配置###########################
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

mybatis:
  # sql语句的打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



---
spring:
  profiles: dev
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/Users/yinjunwu/dev-work/file-temp/uav/
server:
  port: 8088
app:
  swagger2:
    show: true
  security:
    protectUrl: /api/**
    permitUrl: /api/auth/login,/api/auth/register,/api/hello/**
    tokenExpirationTime: 1800
    refreshTokenExpTime: 3600
    tokenSigningKey: ebor123
    tokenHeaderParam: X-Authorization



---
spring:
  profiles: test
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/root/myfile/file-temp/
server:
  port: 10010
app:
  swagger2:
    show: true
  security:
    protectUrl: /api/**
    permitUrl: /api/auth/login,/api/auth/register
    tokenExpirationTime: 1800
    refreshTokenExpTime: 3600
    tokenSigningKey: ebor123
    tokenHeaderParam: X-Authorization



---
spring:
  profiles: prd
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/root/myfile/file-temp/
server:
  port: 80
app:
  swagger2:
    isShow: false
  security:
    protectUrl: /api/**
    permitUrl: /api/auth/login,/api/auth/register
    tokenExpirationTime: 1800
    refreshTokenExpTime: 3600
    tokenSigningKey: ebor123
    tokenHeaderParam: X-Authorization

